package com.pru.lambda.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

import java.util.Date;

@SuperBuilder
@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "main-batchinfo")
public class Batch {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    private String user;

    @DynamoDBAttribute
    private String fileKey;

    @DynamoDBAttribute
    private Date creationDate;

    @DynamoDBAttribute
    private String batchStatus;

    @DynamoDBAttribute
    private String failureReason;

    @DynamoDBAttribute
    private String queryExecutionId;

    @DynamoDBAttribute
    private String s3Path;

    @DynamoDBAttribute
    private Long timeToLive;

}
